version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    url: rediss://red-ck7f1n88elhc73a4819g:6drVBFAvvgEe1nyBbWZgu9FahQdpsZd3@frankfurt-redis.render.com:6379


  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_SCHEMA-postgres}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-user}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-pass}

